version: '3.7'

services:
    db:
        restart: always
        image: mysql/mysql-server@sha256:5b40d96b11333570143d98d3a74100fefadb9abb17b27a95dbc9ad33544ec142
        container_name: mlflow_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - web

    mlflow_server:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            - db
        # ports:
        #     - "5000:5000"
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root /mlflow/artifacts --host 0.0.0.0

        #command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mlflow_server.rule=Host(`mlflow.preislers.de`)"
            - "traefik.http.routers.mlflow_server.entrypoints=websecure"
            - "traefik.http.routers.mlflow_server.tls.certresolver=letsencrypt"
            - "traefik.http.services.mlflow_server.loadbalancer.server.port=5000"
        volumes:
            - ./artifacts:/mlflow/artifacts
        networks:
            - web

volumes:
    dbdata:
    minio_data:
    artifacts:


networks:
    web:
        external: true
